var DOMParser, request, xpath;

DOMParser = require('xmldom').DOMParser;

xpath = require('xpath');

request = require('request');

module.exports = {
  getAddress: function(company, callback) {
    var baseUrl, ref, url;
    baseUrl = (ref = process.env.SEC_EDGAR_URL) != null ? ref : 'http://www.sec.gov/cgi-bin/browse-edgar';
    url = baseUrl + "?action=getcompany&output=atom&start=0&count=1&CIK=" + company;
    return request(url, function(error, response, body) {
      var address, city, dom, state, street1, street2, zip;
      if (error != null) {
        return callback(error);
      } else {
        dom = new DOMParser().parseFromString(body);
        address = xpath.select('/feed/company-info/addresses/address[@type=\'business\']', dom)[0];
        if (address == null) {
          address = xpath.select('/feed/company-info/addresses/address[@type=\'mailing\']', dom)[0];
        }
        street1 = xpath.select('street1/text()', address).toString();
        street2 = xpath.select('street2/text()', address).toString();
        city = xpath.select('city/text()', address).toString();
        state = xpath.select('state/text()', address).toString();
        zip = xpath.select('zip/text()', address).toString();
        return callback(null, {
          street1: street1,
          street2: street2,
          city: city,
          state: state,
          zip: zip
        });
      }
    });
  }
};

// ---
// generated by coffee-script 1.9.2
