module.exports = {
  getYear: function(date) {
    var day, days, fromDate, match, toDate, year;
    if (date == null) {
      date = '';
    }
    if (!date) {
      return -1;
    }
    if (match = date.match(/^from_([a-z]+\d{2})_(\d{4})_to_([a-z]+\d{2})_(\d{4})$/i)) {
      fromDate = Date.parse(match[1] + " " + match[2]);
      if (!isNaN(fromDate)) {
        toDate = Date.parse(match[3] + " " + match[4]);
        if (!isNaN(toDate)) {
          day = 24 * 60 * 60 * 1000;
          days = (toDate - fromDate) / day;
          if ((360 < days && days < 370)) {
            return new Date(toDate).getFullYear();
          }
        }
      }
    }
    if (match = date.match(/^d(\d{4})$/i)) {
      year = parseInt(match[1]);
      if (!isNaN(year)) {
        return year;
      }
    }
    if (match = date.match(/^d(\d{4})q4(ytd)?$/i)) {
      year = parseInt(match[1]);
      if (!isNaN(year)) {
        return year;
      }
    }
    return -1;
  }
};

// ---
// generated by coffee-script 1.9.2
