var DOMParser, request, xpath;

DOMParser = require('xmldom').DOMParser;

xpath = require('xpath');

request = require('request');

module.exports = {
  fetch: function(cik, type, callback) {
    var baseUrl, ref, url;
    baseUrl = (ref = process.env.SEC_EDGAR_URL) != null ? ref : 'http://www.sec.gov/cgi-bin/browse-edgar';
    url = baseUrl + "?action=getcompany&output=atom&start=0&count=1000&CIK=" + cik + "&type=" + type;
    if (parseInt(type) === 4) {
      url = url + "&owner=only";
    }
    return request(url, function(error, response, body) {
      var accessionNumber, date, dom, filingDate, i, id, len, ref1, transaction, transactions;
      if (error != null) {
        return callback(error);
      } else {
        dom = new DOMParser().parseFromString(body);
        cik = parseInt(xpath.select('/feed/company-info/cik/text()', dom));
        transactions = [];
        ref1 = xpath.select('//entry/content', dom);
        for (i = 0, len = ref1.length; i < len; i++) {
          transaction = ref1[i];
          filingDate = xpath.select('filing-date/text()', transaction).toString();
          date = new Date(filingDate + " 14:30:00 GMT");
          accessionNumber = xpath.select('accession-nunber/text()', transaction).toString();
          id = accessionNumber.replace(/-/g, '');
          type = xpath.select('filing-type/text()', transaction).toString();
          transactions.push({
            date: date,
            cik: cik,
            id: id,
            type: type
          });
        }
        return callback(null, transactions);
      }
    });
  }
};

// ---
// generated by coffee-script 1.9.2
